# Generated by Django 2.2.4 on 2019-09-03 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CouncilName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_name', models.CharField(max_length=200)),
                ('council_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.Council')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('City_state_zip', models.CharField(max_length=100)),
                ('first_degree_date', models.DateTimeField(blank=True, null=True)),
                ('second_degree_date', models.DateTimeField(blank=True, null=True)),
                ('third_degree_date', models.DateTimeField(blank=True, null=True)),
                ('reentry_date', models.DateTimeField(blank=True, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('A', 'Associate'), ('I', 'Insurance'), ('N', 'Inactive')], default='A', max_length=1, verbose_name='Membership Type')),
                ('membership_class', models.CharField(blank=True, choices=[('H', 'H. Honorary'), ('L', 'L. Honorary Life')], max_length=1, verbose_name='Membership Class')),
                ('assembly_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('council_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.CouncilName')),
                ('council_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.Council')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('installed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('member_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.Profile')),
            ],
        ),
    ]
