# Generated by Django 2.2.4 on 2019-09-10 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='installed_date',
        ),
        migrations.RemoveField(
            model_name='position',
            name='member_number',
        ),
        migrations.CreateModel(
            name='OfficersTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colbn_year', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('installed_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('council_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.Council')),
                ('membership_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.Profile')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='council.Position')),
            ],
        ),
    ]
